STEPPER_MOTOR(Motor1, CoilA_Motor1, CoilB_Motor1, Yes)
STEPPER_MOTOR(Motor2, CoilA_Motor2, CoilB_Motor2, Yes)
STEPPER_MOTOR(Motor3, CoilA_Motor3, CoilB_Motor3, Yes)
STEPPER_MOTOR(Motor4, CoilA_Motor4, CoilB_Motor4, No)
STEPPER_MOTOR(Motor5, CoilA_Motor5, CoilB_Motor5, No)
STEPPER_MOTOR(Motor6, CoilA_Motor6, CoilB_Motor6, No)
STEPPER_MOTOR(Motor7, CoilA_Motor7, CoilB_Motor7, Yes)