BUTTON(Btn1, BTN1_PORT, BTN1_DIR, BTN1_ANSEL, BTN1_PULLUP, BTN1_PIN, iDeb, iDeb)
BUTTON(Btn2, BTN2_PORT, BTN2_DIR, BTN2_ANSEL, BTN2_PULLUP, BTN2_PIN, iDeb, iDeb)
BUTTON(Btn3, BTN3_PORT, BTN3_DIR, BTN3_ANSEL, BTN3_PULLUP, BTN3_PIN, iDeb, iDeb)
