STEPPER_MOTOR(Motor1, CoilA_Motor1, CoilB_Motor1, Led_Motor1)
STEPPER_MOTOR(Motor2, CoilA_Motor2, CoilB_Motor2, Led_Motor2)
STEPPER_MOTOR(Motor3, CoilA_Motor3, CoilB_Motor3, Led_Motor3)
STEPPER_MOTOR(Motor4, CoilA_Motor4, CoilB_Motor4, Led_Motor4)
STEPPER_MOTOR(Motor5, CoilA_Motor5, CoilB_Motor5, Led_Motor5)
STEPPER_MOTOR(Motor6, CoilA_Motor6, CoilB_Motor6, Led_Motor6)
STEPPER_MOTOR(Motor7, CoilA_Motor7, CoilB_Motor7, Led_Motor7)